### ISSUE TITLE
Allow oneToMany tables to have a `common` block that is applied to every item

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/adtl#33]
This should be specified in adtl.tables:

```toml
[adtl.tables.observation.common]
visit_id = { field = "visit_id", sensitive = true }
subject_id = { field = "subj_id", sensitive = true }
```
